/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { z as zod } from 'zod';

/**
 * 사용자의 주간 러닝 통계를 조회합니다.
 * @summary 주간 통계 조회
 */
export const getWeeklyStatsQueryWeekOffsetDefault = 0;

export const getWeeklyStatsQueryParams = zod.object({
  weekOffset: zod.number().optional().describe('주 오프셋 (0: 이번주, -1: 지난주)'),
});

/**
 * 사용자의 월간 러닝 통계를 조회합니다.
 * @summary 월간 통계 조회
 */
export const getMonthStatsQueryParams = zod.object({
  year: zod.number().optional().describe('연도'),
  month: zod.number().optional().describe('월'),
  monthOffset: zod.number().optional().describe('월 오프셋'),
});
