/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetMonthStatsParams,
  GetWeeklyStatsParams,
  MonthlyStatsResponse,
  PersonalBestStatsResponse,
  PopularRecommendedCourseResponse,
  WeeklyStatsResponse,
} from '.././';

import { apiAxiosInstance } from '../../utils/apiAxiosInstance';
import type { ErrorType } from '../../utils/apiAxiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 사용자의 주간 러닝 통계를 조회합니다.
 * @summary 주간 통계 조회
 */
export const getWeeklyStats = (
  params?: GetWeeklyStatsParams,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<WeeklyStatsResponse>({ url: `/stats/weekly`, method: 'GET', params, signal }, options);
};

export const getGetWeeklyStatsQueryKey = (params?: GetWeeklyStatsParams) => {
  return [`/stats/weekly`, ...(params ? [params] : [])] as const;
};

export const getGetWeeklyStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getWeeklyStats>>,
  TError = ErrorType<WeeklyStatsResponse>,
>(
  params?: GetWeeklyStatsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyStats>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWeeklyStatsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWeeklyStats>>> = ({ signal }) =>
    getWeeklyStats(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWeeklyStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWeeklyStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getWeeklyStats>>>;
export type GetWeeklyStatsQueryError = ErrorType<WeeklyStatsResponse>;

export function useGetWeeklyStats<
  TData = Awaited<ReturnType<typeof getWeeklyStats>>,
  TError = ErrorType<WeeklyStatsResponse>,
>(
  params: undefined | GetWeeklyStatsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyStats>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklyStats>>,
          TError,
          Awaited<ReturnType<typeof getWeeklyStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWeeklyStats<
  TData = Awaited<ReturnType<typeof getWeeklyStats>>,
  TError = ErrorType<WeeklyStatsResponse>,
>(
  params?: GetWeeklyStatsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyStats>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklyStats>>,
          TError,
          Awaited<ReturnType<typeof getWeeklyStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWeeklyStats<
  TData = Awaited<ReturnType<typeof getWeeklyStats>>,
  TError = ErrorType<WeeklyStatsResponse>,
>(
  params?: GetWeeklyStatsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyStats>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 주간 통계 조회
 */

export function useGetWeeklyStats<
  TData = Awaited<ReturnType<typeof getWeeklyStats>>,
  TError = ErrorType<WeeklyStatsResponse>,
>(
  params?: GetWeeklyStatsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyStats>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetWeeklyStatsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 가장 인기 있는 추천 코스 TOP 10을 조회합니다.
 * @summary 인기 추천 코스 TOP 10 조회
 */
export const getPopularRecommendedCourses = (
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<PopularRecommendedCourseResponse[]>(
    { url: `/stats/popular-courses`, method: 'GET', signal },
    options,
  );
};

export const getGetPopularRecommendedCoursesQueryKey = () => {
  return [`/stats/popular-courses`] as const;
};

export const getGetPopularRecommendedCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof getPopularRecommendedCourses>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularRecommendedCourses>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPopularRecommendedCoursesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPopularRecommendedCourses>>> = ({ signal }) =>
    getPopularRecommendedCourses(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPopularRecommendedCourses>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPopularRecommendedCoursesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPopularRecommendedCourses>>
>;
export type GetPopularRecommendedCoursesQueryError = ErrorType<unknown>;

export function useGetPopularRecommendedCourses<
  TData = Awaited<ReturnType<typeof getPopularRecommendedCourses>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularRecommendedCourses>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPopularRecommendedCourses>>,
          TError,
          Awaited<ReturnType<typeof getPopularRecommendedCourses>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPopularRecommendedCourses<
  TData = Awaited<ReturnType<typeof getPopularRecommendedCourses>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularRecommendedCourses>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPopularRecommendedCourses>>,
          TError,
          Awaited<ReturnType<typeof getPopularRecommendedCourses>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPopularRecommendedCourses<
  TData = Awaited<ReturnType<typeof getPopularRecommendedCourses>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularRecommendedCourses>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 인기 추천 코스 TOP 10 조회
 */

export function useGetPopularRecommendedCourses<
  TData = Awaited<ReturnType<typeof getPopularRecommendedCourses>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularRecommendedCourses>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPopularRecommendedCoursesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 사용자의 개인 베스트 러닝 기록을 조회합니다.
 * @summary 개인 베스트 기록 조회
 */
export const getPersonalBestStats = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<PersonalBestStatsResponse>({ url: `/stats/personal-best`, method: 'GET', signal }, options);
};

export const getGetPersonalBestStatsQueryKey = () => {
  return [`/stats/personal-best`] as const;
};

export const getGetPersonalBestStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPersonalBestStats>>,
  TError = ErrorType<PersonalBestStatsResponse>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPersonalBestStats>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPersonalBestStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPersonalBestStats>>> = ({ signal }) =>
    getPersonalBestStats(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPersonalBestStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPersonalBestStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getPersonalBestStats>>>;
export type GetPersonalBestStatsQueryError = ErrorType<PersonalBestStatsResponse>;

export function useGetPersonalBestStats<
  TData = Awaited<ReturnType<typeof getPersonalBestStats>>,
  TError = ErrorType<PersonalBestStatsResponse>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPersonalBestStats>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPersonalBestStats>>,
          TError,
          Awaited<ReturnType<typeof getPersonalBestStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPersonalBestStats<
  TData = Awaited<ReturnType<typeof getPersonalBestStats>>,
  TError = ErrorType<PersonalBestStatsResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPersonalBestStats>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPersonalBestStats>>,
          TError,
          Awaited<ReturnType<typeof getPersonalBestStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPersonalBestStats<
  TData = Awaited<ReturnType<typeof getPersonalBestStats>>,
  TError = ErrorType<PersonalBestStatsResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPersonalBestStats>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 개인 베스트 기록 조회
 */

export function useGetPersonalBestStats<
  TData = Awaited<ReturnType<typeof getPersonalBestStats>>,
  TError = ErrorType<PersonalBestStatsResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPersonalBestStats>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPersonalBestStatsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 사용자의 월간 러닝 통계를 조회합니다.
 * @summary 월간 통계 조회
 */
export const getMonthStats = (
  params?: GetMonthStatsParams,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<MonthlyStatsResponse>({ url: `/stats/monthly`, method: 'GET', params, signal }, options);
};

export const getGetMonthStatsQueryKey = (params?: GetMonthStatsParams) => {
  return [`/stats/monthly`, ...(params ? [params] : [])] as const;
};

export const getGetMonthStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMonthStats>>,
  TError = ErrorType<MonthlyStatsResponse>,
>(
  params?: GetMonthStatsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonthStats>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMonthStatsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMonthStats>>> = ({ signal }) =>
    getMonthStats(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMonthStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMonthStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getMonthStats>>>;
export type GetMonthStatsQueryError = ErrorType<MonthlyStatsResponse>;

export function useGetMonthStats<
  TData = Awaited<ReturnType<typeof getMonthStats>>,
  TError = ErrorType<MonthlyStatsResponse>,
>(
  params: undefined | GetMonthStatsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonthStats>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonthStats>>,
          TError,
          Awaited<ReturnType<typeof getMonthStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMonthStats<
  TData = Awaited<ReturnType<typeof getMonthStats>>,
  TError = ErrorType<MonthlyStatsResponse>,
>(
  params?: GetMonthStatsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonthStats>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonthStats>>,
          TError,
          Awaited<ReturnType<typeof getMonthStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMonthStats<
  TData = Awaited<ReturnType<typeof getMonthStats>>,
  TError = ErrorType<MonthlyStatsResponse>,
>(
  params?: GetMonthStatsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonthStats>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 월간 통계 조회
 */

export function useGetMonthStats<
  TData = Awaited<ReturnType<typeof getMonthStats>>,
  TError = ErrorType<MonthlyStatsResponse>,
>(
  params?: GetMonthStatsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonthStats>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMonthStatsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
