/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

import { apiAxiosInstance } from '../../utils/apiAxiosInstance';
import type { ErrorType } from '../../utils/apiAxiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 코스의 좋아요 상태를 토글합니다. 좋아요가 설정되어 있으면 취소하고, 그렇지 않으면 설정합니다.
 * @summary 코스 좋아요 토글
 */
export const toggleLike = (
  courseId: number,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<void>({ url: `/like/${courseId}`, method: 'POST', signal }, options);
};

export const getToggleLikeMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof toggleLike>>, TError, { courseId: number }, TContext>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof toggleLike>>, TError, { courseId: number }, TContext> => {
  const mutationKey = ['toggleLike'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleLike>>, { courseId: number }> = props => {
    const { courseId } = props ?? {};

    return toggleLike(courseId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ToggleLikeMutationResult = NonNullable<Awaited<ReturnType<typeof toggleLike>>>;

export type ToggleLikeMutationError = ErrorType<void>;

/**
 * @summary 코스 좋아요 토글
 */
export const useToggleLike = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof toggleLike>>, TError, { courseId: number }, TContext>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof toggleLike>>, TError, { courseId: number }, TContext> => {
  const mutationOptions = getToggleLikeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
