/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { z as zod } from 'zod';

/**
 * 코스의 좋아요 상태를 토글합니다. 좋아요가 설정되어 있으면 취소하고, 그렇지 않으면 설정합니다.
 * @summary 코스 좋아요 토글
 */
export const toggleLikeParams = zod.object({
  courseId: zod.number().describe('코스 ID'),
});
