/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { z as zod } from 'zod';

/**
 * 사용자의 프로필 정보를 수정합니다.
 * @summary 사용자 프로필 수정
 */
export const updateProfileBody = zod.object({
  nickname: zod.string().optional(),
  profileImage: zod.string().optional(),
});

/**
 * 입력한 닉네임의 사용 가능 여부를 확인합니다.
 * @summary 닉네임 중복 확인
 */
export const checkNicknameQueryParams = zod.object({
  nickname: zod.string().describe('확인할 닉네임'),
});
