/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type { GetAccessToken200, GetAccessToken401, Reissue200, Reissue401 } from ".././";

import type { ErrorType } from "../../utils/apiAxiosInstance";
import { apiAxiosInstance } from "../../utils/apiAxiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 리프레시 토큰을 사용하여 새로운 액세스 토큰을 발급합니다.
 * @summary 액세스 토큰 재발급
 */
export const reissue = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<Reissue200>({ url: `/auth/refresh`, method: "POST", signal }, options);
};

export const getReissueMutationOptions = <TError = ErrorType<Reissue401>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof reissue>>, TError, void, TContext>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof reissue>>, TError, void, TContext> => {
  const mutationKey = ["reissue"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof reissue>>, void> = () => {
    return reissue(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReissueMutationResult = NonNullable<Awaited<ReturnType<typeof reissue>>>;

export type ReissueMutationError = ErrorType<Reissue401>;

/**
 * @summary 액세스 토큰 재발급
 */
export const useReissue = <TError = ErrorType<Reissue401>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof reissue>>, TError, void, TContext>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof reissue>>, TError, void, TContext> => {
  const mutationOptions = getReissueMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 사용자 로그아웃을 처리합니다.
 * @summary 로그아웃
 */
export const logout = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<string>({ url: `/auth/logout`, method: "POST", signal }, options);
};

export const getLogoutMutationOptions = <TError = ErrorType<string>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext> => {
  const mutationKey = ["logout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
    return logout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>;

export type LogoutMutationError = ErrorType<string>;

/**
 * @summary 로그아웃
 */
export const useLogout = <TError = ErrorType<string>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof logout>>, TError, void, TContext> => {
  const mutationOptions = getLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 리프레시 토큰을 사용하여 액세스 토큰을 발급합니다.
 * @summary 액세스 토큰 발급
 */
export const getAccessToken = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<GetAccessToken200>({ url: `/auth/token`, method: "GET", signal }, options);
};

export const getGetAccessTokenQueryKey = () => {
  return [`/auth/token`] as const;
};

export const getGetAccessTokenQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccessToken>>,
  TError = ErrorType<GetAccessToken401>
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessToken>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAccessTokenQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccessToken>>> = ({ signal }) =>
    getAccessToken(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAccessToken>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAccessTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getAccessToken>>>;
export type GetAccessTokenQueryError = ErrorType<GetAccessToken401>;

export function useGetAccessToken<
  TData = Awaited<ReturnType<typeof getAccessToken>>,
  TError = ErrorType<GetAccessToken401>
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessToken>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccessToken>>,
          TError,
          Awaited<ReturnType<typeof getAccessToken>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAccessToken<
  TData = Awaited<ReturnType<typeof getAccessToken>>,
  TError = ErrorType<GetAccessToken401>
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessToken>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccessToken>>,
          TError,
          Awaited<ReturnType<typeof getAccessToken>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAccessToken<
  TData = Awaited<ReturnType<typeof getAccessToken>>,
  TError = ErrorType<GetAccessToken401>
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessToken>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 액세스 토큰 발급
 */

export function useGetAccessToken<
  TData = Awaited<ReturnType<typeof getAccessToken>>,
  TError = ErrorType<GetAccessToken401>
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessToken>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAccessTokenQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
