/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  FriendResponse,
  ReceivedFriendRequestResponse,
  SendFriendRequestParams,
  SentFriendRequestResponse,
} from '.././';

import { apiAxiosInstance } from '../../utils/apiAxiosInstance';
import type { ErrorType } from '../../utils/apiAxiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 다른 사용자에게 친구 요청을 전송합니다.
 * @summary 친구 요청 전송
 */
export const sendFriendRequest = (
  params: SendFriendRequestParams,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<void>({ url: `/friends/request`, method: 'POST', params, signal }, options);
};

export const getSendFriendRequestMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendFriendRequest>>,
    TError,
    { params: SendFriendRequestParams },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendFriendRequest>>,
  TError,
  { params: SendFriendRequestParams },
  TContext
> => {
  const mutationKey = ['sendFriendRequest'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendFriendRequest>>,
    { params: SendFriendRequestParams }
  > = props => {
    const { params } = props ?? {};

    return sendFriendRequest(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendFriendRequestMutationResult = NonNullable<Awaited<ReturnType<typeof sendFriendRequest>>>;

export type SendFriendRequestMutationError = ErrorType<void>;

/**
 * @summary 친구 요청 전송
 */
export const useSendFriendRequest = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sendFriendRequest>>,
      TError,
      { params: SendFriendRequestParams },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sendFriendRequest>>,
  TError,
  { params: SendFriendRequestParams },
  TContext
> => {
  const mutationOptions = getSendFriendRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 받은 친구 요청을 거절합니다.
 * @summary 친구 요청 거절
 */
export const rejectFriendRequest = (
  requesterId: number,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<void>({ url: `/friends/request/reject/${requesterId}`, method: 'POST', signal }, options);
};

export const getRejectFriendRequestMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rejectFriendRequest>>,
    TError,
    { requesterId: number },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof rejectFriendRequest>>, TError, { requesterId: number }, TContext> => {
  const mutationKey = ['rejectFriendRequest'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rejectFriendRequest>>,
    { requesterId: number }
  > = props => {
    const { requesterId } = props ?? {};

    return rejectFriendRequest(requesterId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RejectFriendRequestMutationResult = NonNullable<Awaited<ReturnType<typeof rejectFriendRequest>>>;

export type RejectFriendRequestMutationError = ErrorType<void>;

/**
 * @summary 친구 요청 거절
 */
export const useRejectFriendRequest = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rejectFriendRequest>>,
      TError,
      { requesterId: number },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof rejectFriendRequest>>, TError, { requesterId: number }, TContext> => {
  const mutationOptions = getRejectFriendRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 받은 친구 요청을 수락합니다.
 * @summary 친구 요청 수락
 */
export const acceptFriendRequest = (
  requesterId: number,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<void>({ url: `/friends/request/accept/${requesterId}`, method: 'POST', signal }, options);
};

export const getAcceptFriendRequestMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptFriendRequest>>,
    TError,
    { requesterId: number },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof acceptFriendRequest>>, TError, { requesterId: number }, TContext> => {
  const mutationKey = ['acceptFriendRequest'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptFriendRequest>>,
    { requesterId: number }
  > = props => {
    const { requesterId } = props ?? {};

    return acceptFriendRequest(requesterId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcceptFriendRequestMutationResult = NonNullable<Awaited<ReturnType<typeof acceptFriendRequest>>>;

export type AcceptFriendRequestMutationError = ErrorType<void>;

/**
 * @summary 친구 요청 수락
 */
export const useAcceptFriendRequest = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof acceptFriendRequest>>,
      TError,
      { requesterId: number },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof acceptFriendRequest>>, TError, { requesterId: number }, TContext> => {
  const mutationOptions = getAcceptFriendRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 내 친구 목록을 조회합니다.
 * @summary 내 친구 목록 조회
 */
export const getMyFriends = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<FriendResponse[]>({ url: `/friends`, method: 'GET', signal }, options);
};

export const getGetMyFriendsQueryKey = () => {
  return [`/friends`] as const;
};

export const getGetMyFriendsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyFriends>>,
  TError = ErrorType<FriendResponse[]>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFriends>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyFriendsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyFriends>>> = ({ signal }) =>
    getMyFriends(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyFriends>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyFriendsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyFriends>>>;
export type GetMyFriendsQueryError = ErrorType<FriendResponse[]>;

export function useGetMyFriends<TData = Awaited<ReturnType<typeof getMyFriends>>, TError = ErrorType<FriendResponse[]>>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFriends>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyFriends>>,
          TError,
          Awaited<ReturnType<typeof getMyFriends>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyFriends<TData = Awaited<ReturnType<typeof getMyFriends>>, TError = ErrorType<FriendResponse[]>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFriends>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyFriends>>,
          TError,
          Awaited<ReturnType<typeof getMyFriends>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyFriends<TData = Awaited<ReturnType<typeof getMyFriends>>, TError = ErrorType<FriendResponse[]>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFriends>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 내 친구 목록 조회
 */

export function useGetMyFriends<TData = Awaited<ReturnType<typeof getMyFriends>>, TError = ErrorType<FriendResponse[]>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFriends>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyFriendsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 내가 보낸 친구 요청 목록을 조회합니다.
 * @summary 보낸 친구 요청 목록 조회
 */
export const getSentMyRequests = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<SentFriendRequestResponse[]>(
    { url: `/friends/request/sent`, method: 'GET', signal },
    options,
  );
};

export const getGetSentMyRequestsQueryKey = () => {
  return [`/friends/request/sent`] as const;
};

export const getGetSentMyRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSentMyRequests>>,
  TError = ErrorType<SentFriendRequestResponse[]>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSentMyRequests>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSentMyRequestsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSentMyRequests>>> = ({ signal }) =>
    getSentMyRequests(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSentMyRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSentMyRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof getSentMyRequests>>>;
export type GetSentMyRequestsQueryError = ErrorType<SentFriendRequestResponse[]>;

export function useGetSentMyRequests<
  TData = Awaited<ReturnType<typeof getSentMyRequests>>,
  TError = ErrorType<SentFriendRequestResponse[]>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSentMyRequests>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSentMyRequests>>,
          TError,
          Awaited<ReturnType<typeof getSentMyRequests>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSentMyRequests<
  TData = Awaited<ReturnType<typeof getSentMyRequests>>,
  TError = ErrorType<SentFriendRequestResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSentMyRequests>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSentMyRequests>>,
          TError,
          Awaited<ReturnType<typeof getSentMyRequests>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSentMyRequests<
  TData = Awaited<ReturnType<typeof getSentMyRequests>>,
  TError = ErrorType<SentFriendRequestResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSentMyRequests>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 보낸 친구 요청 목록 조회
 */

export function useGetSentMyRequests<
  TData = Awaited<ReturnType<typeof getSentMyRequests>>,
  TError = ErrorType<SentFriendRequestResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSentMyRequests>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSentMyRequestsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 내가 받은 친구 요청 목록을 조회합니다.
 * @summary 받은 친구 요청 목록 조회
 */
export const getReceivedMyRequests = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<ReceivedFriendRequestResponse[]>(
    { url: `/friends/request/received`, method: 'GET', signal },
    options,
  );
};

export const getGetReceivedMyRequestsQueryKey = () => {
  return [`/friends/request/received`] as const;
};

export const getGetReceivedMyRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof getReceivedMyRequests>>,
  TError = ErrorType<ReceivedFriendRequestResponse[]>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceivedMyRequests>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReceivedMyRequestsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReceivedMyRequests>>> = ({ signal }) =>
    getReceivedMyRequests(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReceivedMyRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReceivedMyRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof getReceivedMyRequests>>>;
export type GetReceivedMyRequestsQueryError = ErrorType<ReceivedFriendRequestResponse[]>;

export function useGetReceivedMyRequests<
  TData = Awaited<ReturnType<typeof getReceivedMyRequests>>,
  TError = ErrorType<ReceivedFriendRequestResponse[]>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceivedMyRequests>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReceivedMyRequests>>,
          TError,
          Awaited<ReturnType<typeof getReceivedMyRequests>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReceivedMyRequests<
  TData = Awaited<ReturnType<typeof getReceivedMyRequests>>,
  TError = ErrorType<ReceivedFriendRequestResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceivedMyRequests>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReceivedMyRequests>>,
          TError,
          Awaited<ReturnType<typeof getReceivedMyRequests>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReceivedMyRequests<
  TData = Awaited<ReturnType<typeof getReceivedMyRequests>>,
  TError = ErrorType<ReceivedFriendRequestResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceivedMyRequests>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 받은 친구 요청 목록 조회
 */

export function useGetReceivedMyRequests<
  TData = Awaited<ReturnType<typeof getReceivedMyRequests>>,
  TError = ErrorType<ReceivedFriendRequestResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceivedMyRequests>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetReceivedMyRequestsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 친구 관계를 삭제합니다.
 * @summary 친구 삭제
 */
export const removeFriend = (friendId: number, options?: SecondParameter<typeof apiAxiosInstance>) => {
  return apiAxiosInstance<void>({ url: `/friends/${friendId}`, method: 'DELETE' }, options);
};

export const getRemoveFriendMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof removeFriend>>, TError, { friendId: number }, TContext>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof removeFriend>>, TError, { friendId: number }, TContext> => {
  const mutationKey = ['removeFriend'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeFriend>>, { friendId: number }> = props => {
    const { friendId } = props ?? {};

    return removeFriend(friendId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveFriendMutationResult = NonNullable<Awaited<ReturnType<typeof removeFriend>>>;

export type RemoveFriendMutationError = ErrorType<void>;

/**
 * @summary 친구 삭제
 */
export const useRemoveFriend = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof removeFriend>>, TError, { friendId: number }, TContext>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof removeFriend>>, TError, { friendId: number }, TContext> => {
  const mutationOptions = getRemoveFriendMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
