/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { z as zod } from 'zod';

/**
 * 다른 사용자에게 친구 요청을 전송합니다.
 * @summary 친구 요청 전송
 */
export const sendFriendRequestQueryParams = zod.object({
  targetId: zod.number().describe('친구 요청 대상 사용자 ID'),
});

/**
 * 받은 친구 요청을 거절합니다.
 * @summary 친구 요청 거절
 */
export const rejectFriendRequestParams = zod.object({
  requesterId: zod.number().describe('친구 요청자 ID'),
});

/**
 * 받은 친구 요청을 수락합니다.
 * @summary 친구 요청 수락
 */
export const acceptFriendRequestParams = zod.object({
  requesterId: zod.number().describe('친구 요청자 ID'),
});

/**
 * 친구 관계를 삭제합니다.
 * @summary 친구 삭제
 */
export const removeFriendParams = zod.object({
  friendId: zod.number().describe('삭제할 친구 ID'),
});
