/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateRunningRecordBody, RunningRecordListResponse, RunningRecordResponse } from '.././';

import { apiAxiosInstance } from '../../utils/apiAxiosInstance';
import type { ErrorType } from '../../utils/apiAxiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 소프트 삭제된 러닝 기록을 복구합니다.
 * @summary 러닝 기록 복구
 */
export const restoreRunningRecord = (recordId: number, options?: SecondParameter<typeof apiAxiosInstance>) => {
  return apiAxiosInstance<void>({ url: `/running-record/restore/${recordId}`, method: 'PUT' }, options);
};

export const getRestoreRunningRecordMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof restoreRunningRecord>>,
    TError,
    { recordId: number },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof restoreRunningRecord>>, TError, { recordId: number }, TContext> => {
  const mutationKey = ['restoreRunningRecord'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof restoreRunningRecord>>,
    { recordId: number }
  > = props => {
    const { recordId } = props ?? {};

    return restoreRunningRecord(recordId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RestoreRunningRecordMutationResult = NonNullable<Awaited<ReturnType<typeof restoreRunningRecord>>>;

export type RestoreRunningRecordMutationError = ErrorType<void>;

/**
 * @summary 러닝 기록 복구
 */
export const useRestoreRunningRecord = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof restoreRunningRecord>>,
      TError,
      { recordId: number },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof restoreRunningRecord>>, TError, { recordId: number }, TContext> => {
  const mutationOptions = getRestoreRunningRecordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 사용자의 러닝 기록 목록을 조회합니다.
 * @summary 러닝 기록 목록 조회
 */
export const getRunningRecords = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<RunningRecordListResponse>({ url: `/running-record`, method: 'GET', signal }, options);
};

export const getGetRunningRecordsQueryKey = () => {
  return [`/running-record`] as const;
};

export const getGetRunningRecordsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRunningRecords>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunningRecords>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRunningRecordsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRunningRecords>>> = ({ signal }) =>
    getRunningRecords(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRunningRecords>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRunningRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof getRunningRecords>>>;
export type GetRunningRecordsQueryError = ErrorType<unknown>;

export function useGetRunningRecords<
  TData = Awaited<ReturnType<typeof getRunningRecords>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunningRecords>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunningRecords>>,
          TError,
          Awaited<ReturnType<typeof getRunningRecords>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRunningRecords<
  TData = Awaited<ReturnType<typeof getRunningRecords>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunningRecords>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunningRecords>>,
          TError,
          Awaited<ReturnType<typeof getRunningRecords>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRunningRecords<
  TData = Awaited<ReturnType<typeof getRunningRecords>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunningRecords>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 러닝 기록 목록 조회
 */

export function useGetRunningRecords<
  TData = Awaited<ReturnType<typeof getRunningRecords>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunningRecords>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRunningRecordsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 새로운 러닝 기록을 생성합니다.
 * @summary 러닝 기록 생성
 */
export const createRunningRecord = (
  createRunningRecordBody: CreateRunningRecordBody,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<void>(
    {
      url: `/running-record`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createRunningRecordBody,
      signal,
    },
    options,
  );
};

export const getCreateRunningRecordMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRunningRecord>>,
    TError,
    { data: CreateRunningRecordBody },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createRunningRecord>>,
  TError,
  { data: CreateRunningRecordBody },
  TContext
> => {
  const mutationKey = ['createRunningRecord'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createRunningRecord>>,
    { data: CreateRunningRecordBody }
  > = props => {
    const { data } = props ?? {};

    return createRunningRecord(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateRunningRecordMutationResult = NonNullable<Awaited<ReturnType<typeof createRunningRecord>>>;
export type CreateRunningRecordMutationBody = CreateRunningRecordBody;
export type CreateRunningRecordMutationError = ErrorType<void>;

/**
 * @summary 러닝 기록 생성
 */
export const useCreateRunningRecord = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createRunningRecord>>,
      TError,
      { data: CreateRunningRecordBody },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createRunningRecord>>,
  TError,
  { data: CreateRunningRecordBody },
  TContext
> => {
  const mutationOptions = getCreateRunningRecordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 특정 러닝 기록의 상세 정보를 조회합니다.
 * @summary 러닝 기록 상세 조회
 */
export const getRunningRecord = (
  recordId: number,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<RunningRecordResponse>(
    { url: `/running-record/${recordId}`, method: 'GET', signal },
    options,
  );
};

export const getGetRunningRecordQueryKey = (recordId: number) => {
  return [`/running-record/${recordId}`] as const;
};

export const getGetRunningRecordQueryOptions = <
  TData = Awaited<ReturnType<typeof getRunningRecord>>,
  TError = ErrorType<RunningRecordResponse>,
>(
  recordId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunningRecord>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRunningRecordQueryKey(recordId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRunningRecord>>> = ({ signal }) =>
    getRunningRecord(recordId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!recordId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRunningRecord>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRunningRecordQueryResult = NonNullable<Awaited<ReturnType<typeof getRunningRecord>>>;
export type GetRunningRecordQueryError = ErrorType<RunningRecordResponse>;

export function useGetRunningRecord<
  TData = Awaited<ReturnType<typeof getRunningRecord>>,
  TError = ErrorType<RunningRecordResponse>,
>(
  recordId: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunningRecord>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunningRecord>>,
          TError,
          Awaited<ReturnType<typeof getRunningRecord>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRunningRecord<
  TData = Awaited<ReturnType<typeof getRunningRecord>>,
  TError = ErrorType<RunningRecordResponse>,
>(
  recordId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunningRecord>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunningRecord>>,
          TError,
          Awaited<ReturnType<typeof getRunningRecord>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRunningRecord<
  TData = Awaited<ReturnType<typeof getRunningRecord>>,
  TError = ErrorType<RunningRecordResponse>,
>(
  recordId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunningRecord>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 러닝 기록 상세 조회
 */

export function useGetRunningRecord<
  TData = Awaited<ReturnType<typeof getRunningRecord>>,
  TError = ErrorType<RunningRecordResponse>,
>(
  recordId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunningRecord>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRunningRecordQueryOptions(recordId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 러닝 기록을 소프트 삭제합니다.
 * @summary 러닝 기록 삭제
 */
export const deleteRunningRecord = (recordId: number, options?: SecondParameter<typeof apiAxiosInstance>) => {
  return apiAxiosInstance<void>({ url: `/running-record/${recordId}`, method: 'DELETE' }, options);
};

export const getDeleteRunningRecordMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRunningRecord>>,
    TError,
    { recordId: number },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteRunningRecord>>, TError, { recordId: number }, TContext> => {
  const mutationKey = ['deleteRunningRecord'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRunningRecord>>, { recordId: number }> = props => {
    const { recordId } = props ?? {};

    return deleteRunningRecord(recordId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteRunningRecordMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRunningRecord>>>;

export type DeleteRunningRecordMutationError = ErrorType<void>;

/**
 * @summary 러닝 기록 삭제
 */
export const useDeleteRunningRecord = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteRunningRecord>>,
      TError,
      { recordId: number },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteRunningRecord>>, TError, { recordId: number }, TContext> => {
  const mutationOptions = getDeleteRunningRecordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 소프트 삭제된 러닝 기록 목록을 조회합니다.
 * @summary 삭제된 러닝 기록 목록 조회
 */
export const getDeletedRecords = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<RunningRecordListResponse[]>(
    { url: `/running-record/deleted`, method: 'GET', signal },
    options,
  );
};

export const getGetDeletedRecordsQueryKey = () => {
  return [`/running-record/deleted`] as const;
};

export const getGetDeletedRecordsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDeletedRecords>>,
  TError = ErrorType<RunningRecordListResponse[]>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedRecords>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDeletedRecordsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeletedRecords>>> = ({ signal }) =>
    getDeletedRecords(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDeletedRecords>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDeletedRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof getDeletedRecords>>>;
export type GetDeletedRecordsQueryError = ErrorType<RunningRecordListResponse[]>;

export function useGetDeletedRecords<
  TData = Awaited<ReturnType<typeof getDeletedRecords>>,
  TError = ErrorType<RunningRecordListResponse[]>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedRecords>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeletedRecords>>,
          TError,
          Awaited<ReturnType<typeof getDeletedRecords>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDeletedRecords<
  TData = Awaited<ReturnType<typeof getDeletedRecords>>,
  TError = ErrorType<RunningRecordListResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedRecords>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeletedRecords>>,
          TError,
          Awaited<ReturnType<typeof getDeletedRecords>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDeletedRecords<
  TData = Awaited<ReturnType<typeof getDeletedRecords>>,
  TError = ErrorType<RunningRecordListResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedRecords>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 삭제된 러닝 기록 목록 조회
 */

export function useGetDeletedRecords<
  TData = Awaited<ReturnType<typeof getDeletedRecords>>,
  TError = ErrorType<RunningRecordListResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedRecords>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDeletedRecordsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 러닝 기록을 영구적으로 삭제합니다.
 * @summary 러닝 기록 영구 삭제
 */
export const permanentDeleteRunningRecord = (recordId: number, options?: SecondParameter<typeof apiAxiosInstance>) => {
  return apiAxiosInstance<void>({ url: `/running-record/permanent/${recordId}`, method: 'DELETE' }, options);
};

export const getPermanentDeleteRunningRecordMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof permanentDeleteRunningRecord>>,
    TError,
    { recordId: number },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof permanentDeleteRunningRecord>>,
  TError,
  { recordId: number },
  TContext
> => {
  const mutationKey = ['permanentDeleteRunningRecord'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof permanentDeleteRunningRecord>>,
    { recordId: number }
  > = props => {
    const { recordId } = props ?? {};

    return permanentDeleteRunningRecord(recordId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PermanentDeleteRunningRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof permanentDeleteRunningRecord>>
>;

export type PermanentDeleteRunningRecordMutationError = ErrorType<void>;

/**
 * @summary 러닝 기록 영구 삭제
 */
export const usePermanentDeleteRunningRecord = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof permanentDeleteRunningRecord>>,
      TError,
      { recordId: number },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof permanentDeleteRunningRecord>>,
  TError,
  { recordId: number },
  TContext
> => {
  const mutationOptions = getPermanentDeleteRunningRecordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
