/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { z as zod } from 'zod';

/**
 * 소프트 삭제된 러닝 기록을 복구합니다.
 * @summary 러닝 기록 복구
 */
export const restoreRunningRecordParams = zod.object({
  recordId: zod.number().describe('복구할 러닝 기록 ID'),
});

/**
 * 새로운 러닝 기록을 생성합니다.
 * @summary 러닝 기록 생성
 */
export const createRunningRecordBody = zod.object({
  image: zod.instanceof(File).describe('러닝 기록 이미지'),
  data: zod
    .object({
      pathGeoJson: zod.string().optional(),
      startLatitude: zod.number().optional(),
      startLongitude: zod.number().optional(),
      endLatitude: zod.number().optional(),
      endLongitude: zod.number().optional(),
      startedTime: zod.string().datetime({}).optional(),
      endedTime: zod.string().datetime({}).optional(),
      recommendedCourseId: zod.number().optional(),
    })
    .describe('러닝 기록 데이터'),
});

/**
 * 특정 러닝 기록의 상세 정보를 조회합니다.
 * @summary 러닝 기록 상세 조회
 */
export const getRunningRecordParams = zod.object({
  recordId: zod.number().describe('러닝 기록 ID'),
});

/**
 * 러닝 기록을 소프트 삭제합니다.
 * @summary 러닝 기록 삭제
 */
export const deleteRunningRecordParams = zod.object({
  recordId: zod.number().describe('러닝 기록 ID'),
});

/**
 * 러닝 기록을 영구적으로 삭제합니다.
 * @summary 러닝 기록 영구 삭제
 */
export const permanentDeleteRunningRecordParams = zod.object({
  recordId: zod.number().describe('영구 삭제할 러닝 기록 ID'),
});
