/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */

export interface BookmarkedCourseListResponse {
  bookmarkId?: number;
  courseId?: number;
  imageUrl?: string;
  title?: string;
  totalDistance?: number;
  endLocationName?: string;
  bookmarkedAt?: string;
}
