/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import type { RunningRecordRequest } from './runningRecordRequest';

export type CreateRunningRecordBody = {
  /** 러닝 기록 이미지 */
  image: Blob;
  data: RunningRecordRequest;
};
