/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import type { GetAllRecommendedCoursesSortType } from './getAllRecommendedCoursesSortType';

export type GetAllRecommendedCoursesParams = {
  /**
   * 정렬 타입 (LIKE: 좋아요순, RECENT: 최신순)
   */
  sortType?: GetAllRecommendedCoursesSortType;
};
