/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */

export type GetWeeklyStatsParams = {
  /**
   * 주 오프셋 (0: 이번주, -1: 지난주)
   */
  weekOffset?: number;
};
