/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import type { BestMonthRecord } from './bestMonthRecord';

export interface PersonalBestStatsResponse {
  longestDistance?: number;
  fastestPace?: number;
  longestTime?: number;
  totalDistance?: number;
  totalRuns?: number;
  bestMonthRecord?: BestMonthRecord;
}
