/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import type { JsonNode } from './jsonNode';
import type { CourseTopRunner } from './courseTopRunner';

export interface RecommendedCourseResponse {
  id?: number;
  userId?: number;
  userName?: string;
  title?: string;
  description?: string;
  startLocationName?: string;
  endLocationName?: string;
  pathGeoJson?: JsonNode;
  totalDistance?: number;
  likeCount?: number;
  isLiked?: boolean;
  isBookmarked?: boolean;
  totalCompletionCount?: number;
  uniqueRunnerCount?: number;
  averageCompletionTime?: number;
  averagePace?: number;
  myCompletionCount?: number;
  myBestTime?: number;
  myAveragePace?: number;
  topRunners?: CourseTopRunner[];
}
