/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import type { JsonNode } from './jsonNode';
import type { RecommendedCourseInfo } from './recommendedCourseInfo';

export interface RunningRecordResponse {
  id?: number;
  totalDistance?: number;
  totalTime?: number;
  pace?: number;
  startedTime?: string;
  endedTime?: string;
  startLatitude?: number;
  startLongitude?: number;
  endLatitude?: number;
  endLongitude?: number;
  startLocationName?: string;
  endLocationName?: string;
  pathGeoJson?: JsonNode;
  recommendedCourse?: RecommendedCourseInfo;
  isRegisteredAsCourse?: boolean;
}
