/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import type { RecommendedCourseInfo } from './recommendedCourseInfo';

export interface RunningRecordListResponse {
  id?: number;
  totalDistance?: number;
  totalTime?: number;
  pace?: number;
  endLocationName?: string;
  createAt?: string;
  recommendedCourse?: RecommendedCourseInfo;
}
