/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */

/**
 * 러닝 기록 데이터
 */
export interface RunningRecordRequest {
  pathGeoJson?: string;
  startLatitude?: number;
  startLongitude?: number;
  endLatitude?: number;
  endLongitude?: number;
  startedTime?: string;
  endedTime?: string;
  recommendedCourseId?: number;
}
