/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetNearbyFriendsParams,
  LocationSharingRequest,
  LocationSharingResponse,
  LocationUpdateRequest,
  NearbyFriendResponse,
} from '.././';
  
import { apiAxiosInstance } from '../../utils/apiAxiosInstance';
import type { ErrorType } from '../../utils/apiAxiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 사용자의 현재 위치를 업데이트합니다.
 * @summary 위치 업데이트
 */
export const updateLocation = (
  locationUpdateRequest: LocationUpdateRequest,
  options?: SecondParameter<typeof apiAxiosInstance>,
) => {
  return apiAxiosInstance<void>(
    { url: `/location`, method: 'PATCH', headers: { 'Content-Type': 'application/json' }, data: locationUpdateRequest },
    options,
  );
};

export const getUpdateLocationMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLocation>>,
    TError,
    { data: LocationUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateLocation>>,
  TError,
  { data: LocationUpdateRequest },
  TContext
> => {
  const mutationKey = ['updateLocation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateLocation>>,
    { data: LocationUpdateRequest }
  > = props => {
    const { data } = props ?? {};

    return updateLocation(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateLocationMutationResult = NonNullable<Awaited<ReturnType<typeof updateLocation>>>;
export type UpdateLocationMutationBody = LocationUpdateRequest;
export type UpdateLocationMutationError = ErrorType<void>;

/**
 * @summary 위치 업데이트
 */
export const useUpdateLocation = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateLocation>>,
      TError,
      { data: LocationUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof updateLocation>>, TError, { data: LocationUpdateRequest }, TContext> => {
  const mutationOptions = getUpdateLocationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 사용자의 현재 위치 공유 상태를 조회합니다.
 * @summary 위치 공유 상태 조회
 */
export const getLocationSharingStatus = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<LocationSharingResponse>({ url: `/location/sharing`, method: 'GET', signal }, options);
};

export const getGetLocationSharingStatusQueryKey = () => {
  return [`/location/sharing`] as const;
};

export const getGetLocationSharingStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getLocationSharingStatus>>,
  TError = ErrorType<LocationSharingResponse>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationSharingStatus>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLocationSharingStatusQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationSharingStatus>>> = ({ signal }) =>
    getLocationSharingStatus(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLocationSharingStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLocationSharingStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationSharingStatus>>>;
export type GetLocationSharingStatusQueryError = ErrorType<LocationSharingResponse>;

export function useGetLocationSharingStatus<
  TData = Awaited<ReturnType<typeof getLocationSharingStatus>>,
  TError = ErrorType<LocationSharingResponse>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationSharingStatus>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationSharingStatus>>,
          TError,
          Awaited<ReturnType<typeof getLocationSharingStatus>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLocationSharingStatus<
  TData = Awaited<ReturnType<typeof getLocationSharingStatus>>,
  TError = ErrorType<LocationSharingResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationSharingStatus>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationSharingStatus>>,
          TError,
          Awaited<ReturnType<typeof getLocationSharingStatus>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLocationSharingStatus<
  TData = Awaited<ReturnType<typeof getLocationSharingStatus>>,
  TError = ErrorType<LocationSharingResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationSharingStatus>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 위치 공유 상태 조회
 */

export function useGetLocationSharingStatus<
  TData = Awaited<ReturnType<typeof getLocationSharingStatus>>,
  TError = ErrorType<LocationSharingResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationSharingStatus>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetLocationSharingStatusQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 사용자의 위치 공유 여부를 설정합니다.
 * @summary 위치 공유 설정
 */
export const setLocationSharing = (
  locationSharingRequest: LocationSharingRequest,
  options?: SecondParameter<typeof apiAxiosInstance>,
) => {
  return apiAxiosInstance<LocationSharingResponse>(
    {
      url: `/location/sharing`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: locationSharingRequest,
    },
    options,
  );
};

export const getSetLocationSharingMutationOptions = <
  TError = ErrorType<LocationSharingResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setLocationSharing>>,
    TError,
    { data: LocationSharingRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setLocationSharing>>,
  TError,
  { data: LocationSharingRequest },
  TContext
> => {
  const mutationKey = ['setLocationSharing'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setLocationSharing>>,
    { data: LocationSharingRequest }
  > = props => {
    const { data } = props ?? {};

    return setLocationSharing(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetLocationSharingMutationResult = NonNullable<Awaited<ReturnType<typeof setLocationSharing>>>;
export type SetLocationSharingMutationBody = LocationSharingRequest;
export type SetLocationSharingMutationError = ErrorType<LocationSharingResponse>;

/**
 * @summary 위치 공유 설정
 */
export const useSetLocationSharing = <TError = ErrorType<LocationSharingResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setLocationSharing>>,
      TError,
      { data: LocationSharingRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof setLocationSharing>>,
  TError,
  { data: LocationSharingRequest },
  TContext
> => {
  const mutationOptions = getSetLocationSharingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 지정된 반경 내의 친구 목록을 조회합니다.
 * @summary 근처 친구 조회
 */
export const getNearbyFriends = (
  params?: GetNearbyFriendsParams,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<NearbyFriendResponse[]>({ url: `/location/nearby`, method: 'GET', params, signal }, options);
};

export const getGetNearbyFriendsQueryKey = (params?: GetNearbyFriendsParams) => {
  return [`/location/nearby`, ...(params ? [params] : [])] as const;
};

export const getGetNearbyFriendsQueryOptions = <
  TData = Awaited<ReturnType<typeof getNearbyFriends>>,
  TError = ErrorType<NearbyFriendResponse[]>,
>(
  params?: GetNearbyFriendsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyFriends>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNearbyFriendsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNearbyFriends>>> = ({ signal }) =>
    getNearbyFriends(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNearbyFriends>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNearbyFriendsQueryResult = NonNullable<Awaited<ReturnType<typeof getNearbyFriends>>>;
export type GetNearbyFriendsQueryError = ErrorType<NearbyFriendResponse[]>;

export function useGetNearbyFriends<
  TData = Awaited<ReturnType<typeof getNearbyFriends>>,
  TError = ErrorType<NearbyFriendResponse[]>,
>(
  params: undefined | GetNearbyFriendsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyFriends>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNearbyFriends>>,
          TError,
          Awaited<ReturnType<typeof getNearbyFriends>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNearbyFriends<
  TData = Awaited<ReturnType<typeof getNearbyFriends>>,
  TError = ErrorType<NearbyFriendResponse[]>,
>(
  params?: GetNearbyFriendsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyFriends>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNearbyFriends>>,
          TError,
          Awaited<ReturnType<typeof getNearbyFriends>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNearbyFriends<
  TData = Awaited<ReturnType<typeof getNearbyFriends>>,
  TError = ErrorType<NearbyFriendResponse[]>,
>(
  params?: GetNearbyFriendsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyFriends>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 근처 친구 조회
 */

export function useGetNearbyFriends<
  TData = Awaited<ReturnType<typeof getNearbyFriends>>,
  TError = ErrorType<NearbyFriendResponse[]>,
>(
  params?: GetNearbyFriendsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyFriends>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetNearbyFriendsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
