/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { z as zod } from 'zod';

/**
 * 사용자의 현재 위치를 업데이트합니다.
 * @summary 위치 업데이트
 */
export const updateLocationBody = zod.object({
  latitude: zod.number().optional(),
  longitude: zod.number().optional(),
});

/**
 * 사용자의 위치 공유 여부를 설정합니다.
 * @summary 위치 공유 설정
 */
export const setLocationSharingBody = zod.object({
  isSharing: zod.boolean().optional(),
});

/**
 * 지정된 반경 내의 친구 목록을 조회합니다.
 * @summary 근처 친구 조회
 */
export const getNearbyFriendsQueryRadiusDefault = 0.5;

export const getNearbyFriendsQueryParams = zod.object({
  radius: zod.number().default(getNearbyFriendsQueryRadiusDefault).describe('검색 반경 (단위: km)'),
});
