/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { z as zod } from 'zod';

/**
 * 러닝 기록을 기반으로 추천 코스를 생성합니다.
 * @summary 추천 코스 생성
 */
export const createCourseParams = zod.object({
  recordId: zod.number().describe('러닝 기록 ID'),
});

/**
 * 추천 코스의 상세 정보를 조회합니다.
 * @summary 추천 코스 상세 조회
 */
export const getCourseParams = zod.object({
  courseId: zod.number().describe('추천 코스 ID'),
});

/**
 * 추천 코스를 삭제합니다.
 * @summary 추천 코스 삭제
 */
export const deleteCourseParams = zod.object({
  courseId: zod.number().describe('추천 코스 ID'),
});

/**
 * 추천 코스의 제목과 설명을 수정합니다.
 * @summary 추천 코스 수정
 */
export const updateCourseParams = zod.object({
  courseId: zod.number().describe('추천 코스 ID'),
});

export const updateCourseBody = zod.object({
  title: zod.string().optional(),
  description: zod.string().optional(),
});

/**
 * 모든 추천 코스 목록을 정렬 옵션에 따라 조회합니다.
 * @summary 추천 코스 목록 조회
 */
export const getAllRecommendedCoursesQuerySortTypeDefault = 'LIKE';

export const getAllRecommendedCoursesQueryParams = zod.object({
  sortType: zod
    .enum(['LIKE', 'DISTANCE', 'RECENT'])
    .default(getAllRecommendedCoursesQuerySortTypeDefault)
    .describe('정렬 타입 (LIKE: 좋아요순, RECENT: 최신순)'),
});
