/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetAllRecommendedCoursesParams,
  RecommendedCourseListResponse,
  RecommendedCourseMyListResponse,
  RecommendedCourseResponse,
  RecommendedCourseUpdateRequest,
} from '.././';

import { apiAxiosInstance } from '../../utils/apiAxiosInstance';
import type { ErrorType } from '../../utils/apiAxiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 러닝 기록을 기반으로 추천 코스를 생성합니다.
 * @summary 추천 코스 생성
 */
export const createCourse = (
  recordId: number,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<void>({ url: `/course/${recordId}`, method: 'POST', signal }, options);
};

export const getCreateCourseMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof createCourse>>, TError, { recordId: number }, TContext>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof createCourse>>, TError, { recordId: number }, TContext> => {
  const mutationKey = ['createCourse'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCourse>>, { recordId: number }> = props => {
    const { recordId } = props ?? {};

    return createCourse(recordId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCourseMutationResult = NonNullable<Awaited<ReturnType<typeof createCourse>>>;

export type CreateCourseMutationError = ErrorType<void>;

/**
 * @summary 추천 코스 생성
 */
export const useCreateCourse = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createCourse>>, TError, { recordId: number }, TContext>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof createCourse>>, TError, { recordId: number }, TContext> => {
  const mutationOptions = getCreateCourseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 추천 코스의 상세 정보를 조회합니다.
 * @summary 추천 코스 상세 조회
 */
export const getCourse = (
  courseId: number,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<RecommendedCourseResponse>({ url: `/course/${courseId}`, method: 'GET', signal }, options);
};

export const getGetCourseQueryKey = (courseId: number) => {
  return [`/course/${courseId}`] as const;
};

export const getGetCourseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCourse>>,
  TError = ErrorType<RecommendedCourseResponse>,
>(
  courseId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourse>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCourseQueryKey(courseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourse>>> = ({ signal }) =>
    getCourse(courseId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!courseId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCourse>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCourseQueryResult = NonNullable<Awaited<ReturnType<typeof getCourse>>>;
export type GetCourseQueryError = ErrorType<RecommendedCourseResponse>;

export function useGetCourse<
  TData = Awaited<ReturnType<typeof getCourse>>,
  TError = ErrorType<RecommendedCourseResponse>,
>(
  courseId: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourse>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof getCourse>>, TError, Awaited<ReturnType<typeof getCourse>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCourse<
  TData = Awaited<ReturnType<typeof getCourse>>,
  TError = ErrorType<RecommendedCourseResponse>,
>(
  courseId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourse>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCourse>>,
          TError,
          Awaited<ReturnType<typeof getCourse>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCourse<
  TData = Awaited<ReturnType<typeof getCourse>>,
  TError = ErrorType<RecommendedCourseResponse>,
>(
  courseId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourse>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 추천 코스 상세 조회
 */

export function useGetCourse<
  TData = Awaited<ReturnType<typeof getCourse>>,
  TError = ErrorType<RecommendedCourseResponse>,
>(
  courseId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourse>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCourseQueryOptions(courseId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 추천 코스를 삭제합니다.
 * @summary 추천 코스 삭제
 */
export const deleteCourse = (courseId: number, options?: SecondParameter<typeof apiAxiosInstance>) => {
  return apiAxiosInstance<void>({ url: `/course/${courseId}`, method: 'DELETE' }, options);
};

export const getDeleteCourseMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteCourse>>, TError, { courseId: number }, TContext>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteCourse>>, TError, { courseId: number }, TContext> => {
  const mutationKey = ['deleteCourse'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCourse>>, { courseId: number }> = props => {
    const { courseId } = props ?? {};

    return deleteCourse(courseId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCourseMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCourse>>>;

export type DeleteCourseMutationError = ErrorType<void>;

/**
 * @summary 추천 코스 삭제
 */
export const useDeleteCourse = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteCourse>>, TError, { courseId: number }, TContext>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteCourse>>, TError, { courseId: number }, TContext> => {
  const mutationOptions = getDeleteCourseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 추천 코스의 제목과 설명을 수정합니다.
 * @summary 추천 코스 수정
 */
export const updateCourse = (
  courseId: number,
  recommendedCourseUpdateRequest: RecommendedCourseUpdateRequest,
  options?: SecondParameter<typeof apiAxiosInstance>,
) => {
  return apiAxiosInstance<void>(
    {
      url: `/course/${courseId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: recommendedCourseUpdateRequest,
    },
    options,
  );
};

export const getUpdateCourseMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCourse>>,
    TError,
    { courseId: number; data: RecommendedCourseUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCourse>>,
  TError,
  { courseId: number; data: RecommendedCourseUpdateRequest },
  TContext
> => {
  const mutationKey = ['updateCourse'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCourse>>,
    { courseId: number; data: RecommendedCourseUpdateRequest }
  > = props => {
    const { courseId, data } = props ?? {};

    return updateCourse(courseId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCourseMutationResult = NonNullable<Awaited<ReturnType<typeof updateCourse>>>;
export type UpdateCourseMutationBody = RecommendedCourseUpdateRequest;
export type UpdateCourseMutationError = ErrorType<void>;

/**
 * @summary 추천 코스 수정
 */
export const useUpdateCourse = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCourse>>,
      TError,
      { courseId: number; data: RecommendedCourseUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCourse>>,
  TError,
  { courseId: number; data: RecommendedCourseUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdateCourseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 모든 추천 코스 목록을 정렬 옵션에 따라 조회합니다.
 * @summary 추천 코스 목록 조회
 */
export const getAllRecommendedCourses = (
  params?: GetAllRecommendedCoursesParams,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<RecommendedCourseListResponse[]>({ url: `/course`, method: 'GET', params, signal }, options);
};

export const getGetAllRecommendedCoursesQueryKey = (params?: GetAllRecommendedCoursesParams) => {
  return [`/course`, ...(params ? [params] : [])] as const;
};

export const getGetAllRecommendedCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllRecommendedCourses>>,
  TError = ErrorType<RecommendedCourseListResponse[]>,
>(
  params?: GetAllRecommendedCoursesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRecommendedCourses>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllRecommendedCoursesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllRecommendedCourses>>> = ({ signal }) =>
    getAllRecommendedCourses(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllRecommendedCourses>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllRecommendedCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllRecommendedCourses>>>;
export type GetAllRecommendedCoursesQueryError = ErrorType<RecommendedCourseListResponse[]>;

export function useGetAllRecommendedCourses<
  TData = Awaited<ReturnType<typeof getAllRecommendedCourses>>,
  TError = ErrorType<RecommendedCourseListResponse[]>,
>(
  params: undefined | GetAllRecommendedCoursesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRecommendedCourses>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllRecommendedCourses>>,
          TError,
          Awaited<ReturnType<typeof getAllRecommendedCourses>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllRecommendedCourses<
  TData = Awaited<ReturnType<typeof getAllRecommendedCourses>>,
  TError = ErrorType<RecommendedCourseListResponse[]>,
>(
  params?: GetAllRecommendedCoursesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRecommendedCourses>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllRecommendedCourses>>,
          TError,
          Awaited<ReturnType<typeof getAllRecommendedCourses>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllRecommendedCourses<
  TData = Awaited<ReturnType<typeof getAllRecommendedCourses>>,
  TError = ErrorType<RecommendedCourseListResponse[]>,
>(
  params?: GetAllRecommendedCoursesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRecommendedCourses>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 추천 코스 목록 조회
 */

export function useGetAllRecommendedCourses<
  TData = Awaited<ReturnType<typeof getAllRecommendedCourses>>,
  TError = ErrorType<RecommendedCourseListResponse[]>,
>(
  params?: GetAllRecommendedCoursesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRecommendedCourses>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllRecommendedCoursesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 현재 사용자가 생성한 추천 코스 목록을 조회합니다.
 * @summary 내 추천 코스 목록 조회
 */
export const getMyRecommendedCourses = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<RecommendedCourseMyListResponse[]>({ url: `/course/my`, method: 'GET', signal }, options);
};

export const getGetMyRecommendedCoursesQueryKey = () => {
  return [`/course/my`] as const;
};

export const getGetMyRecommendedCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyRecommendedCourses>>,
  TError = ErrorType<RecommendedCourseMyListResponse[]>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRecommendedCourses>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyRecommendedCoursesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyRecommendedCourses>>> = ({ signal }) =>
    getMyRecommendedCourses(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyRecommendedCourses>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyRecommendedCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof getMyRecommendedCourses>>>;
export type GetMyRecommendedCoursesQueryError = ErrorType<RecommendedCourseMyListResponse[]>;

export function useGetMyRecommendedCourses<
  TData = Awaited<ReturnType<typeof getMyRecommendedCourses>>,
  TError = ErrorType<RecommendedCourseMyListResponse[]>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRecommendedCourses>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyRecommendedCourses>>,
          TError,
          Awaited<ReturnType<typeof getMyRecommendedCourses>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyRecommendedCourses<
  TData = Awaited<ReturnType<typeof getMyRecommendedCourses>>,
  TError = ErrorType<RecommendedCourseMyListResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRecommendedCourses>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyRecommendedCourses>>,
          TError,
          Awaited<ReturnType<typeof getMyRecommendedCourses>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyRecommendedCourses<
  TData = Awaited<ReturnType<typeof getMyRecommendedCourses>>,
  TError = ErrorType<RecommendedCourseMyListResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRecommendedCourses>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 내 추천 코스 목록 조회
 */

export function useGetMyRecommendedCourses<
  TData = Awaited<ReturnType<typeof getMyRecommendedCourses>>,
  TError = ErrorType<RecommendedCourseMyListResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyRecommendedCourses>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyRecommendedCoursesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
