/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { z as zod } from 'zod';

/**
 * 코스의 북마크 상태를 설정하거나 해제합니다.
 * @summary 코스 북마크 설정
 */
export const setBookmarkParams = zod.object({
  courseId: zod.number().describe('코스 ID'),
});

export const setBookmarkBody = zod.object({
  isBookmarked: zod.boolean().optional(),
});

/**
 * 특정 코스의 북마크 상태를 조회합니다.
 * @summary 코스 북마크 상태 조회
 */
export const getBookmarkStatusParams = zod.object({
  courseId: zod.number().describe('코스 ID'),
});
