/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * RunRush API
 * 러닝 소셜 플랫폼 RunRush의 REST API 문서
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { BookmarkRequest, BookmarkResponse, BookmarkedCourseListResponse } from '.././';

import { apiAxiosInstance } from '../../utils/apiAxiosInstance';
import type { ErrorType } from '../../utils/apiAxiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 코스의 북마크 상태를 설정하거나 해제합니다.
 * @summary 코스 북마크 설정
 */
export const setBookmark = (
  courseId: number,
  bookmarkRequest: BookmarkRequest,
  options?: SecondParameter<typeof apiAxiosInstance>,
) => {
  return apiAxiosInstance<BookmarkResponse>(
    {
      url: `/course/bookmark/${courseId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: bookmarkRequest,
    },
    options,
  );
};

export const getSetBookmarkMutationOptions = <TError = ErrorType<BookmarkResponse>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setBookmark>>,
    TError,
    { courseId: number; data: BookmarkRequest },
    TContext
  >;
  request?: SecondParameter<typeof apiAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setBookmark>>,
  TError,
  { courseId: number; data: BookmarkRequest },
  TContext
> => {
  const mutationKey = ['setBookmark'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setBookmark>>,
    { courseId: number; data: BookmarkRequest }
  > = props => {
    const { courseId, data } = props ?? {};

    return setBookmark(courseId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetBookmarkMutationResult = NonNullable<Awaited<ReturnType<typeof setBookmark>>>;
export type SetBookmarkMutationBody = BookmarkRequest;
export type SetBookmarkMutationError = ErrorType<BookmarkResponse>;

/**
 * @summary 코스 북마크 설정
 */
export const useSetBookmark = <TError = ErrorType<BookmarkResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setBookmark>>,
      TError,
      { courseId: number; data: BookmarkRequest },
      TContext
    >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof setBookmark>>,
  TError,
  { courseId: number; data: BookmarkRequest },
  TContext
> => {
  const mutationOptions = getSetBookmarkMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 특정 코스의 북마크 상태를 조회합니다.
 * @summary 코스 북마크 상태 조회
 */
export const getBookmarkStatus = (
  courseId: number,
  options?: SecondParameter<typeof apiAxiosInstance>,
  signal?: AbortSignal,
) => {
  return apiAxiosInstance<BookmarkResponse>(
    { url: `/course/bookmark/status/${courseId}`, method: 'GET', signal },
    options,
  );
};

export const getGetBookmarkStatusQueryKey = (courseId: number) => {
  return [`/course/bookmark/status/${courseId}`] as const;
};

export const getGetBookmarkStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getBookmarkStatus>>,
  TError = ErrorType<BookmarkResponse>,
>(
  courseId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBookmarkStatusQueryKey(courseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookmarkStatus>>> = ({ signal }) =>
    getBookmarkStatus(courseId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!courseId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBookmarkStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBookmarkStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getBookmarkStatus>>>;
export type GetBookmarkStatusQueryError = ErrorType<BookmarkResponse>;

export function useGetBookmarkStatus<
  TData = Awaited<ReturnType<typeof getBookmarkStatus>>,
  TError = ErrorType<BookmarkResponse>,
>(
  courseId: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkStatus>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkStatus>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetBookmarkStatus<
  TData = Awaited<ReturnType<typeof getBookmarkStatus>>,
  TError = ErrorType<BookmarkResponse>,
>(
  courseId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkStatus>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkStatus>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetBookmarkStatus<
  TData = Awaited<ReturnType<typeof getBookmarkStatus>>,
  TError = ErrorType<BookmarkResponse>,
>(
  courseId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 코스 북마크 상태 조회
 */

export function useGetBookmarkStatus<
  TData = Awaited<ReturnType<typeof getBookmarkStatus>>,
  TError = ErrorType<BookmarkResponse>,
>(
  courseId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetBookmarkStatusQueryOptions(courseId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 사용자가 북마크한 코스 목록을 조회합니다.
 * @summary 내 북마크 코스 목록 조회
 */
export const getMyBookmarkedCourses = (options?: SecondParameter<typeof apiAxiosInstance>, signal?: AbortSignal) => {
  return apiAxiosInstance<BookmarkedCourseListResponse[]>(
    { url: `/course/bookmark/my`, method: 'GET', signal },
    options,
  );
};

export const getGetMyBookmarkedCoursesQueryKey = () => {
  return [`/course/bookmark/my`] as const;
};

export const getGetMyBookmarkedCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyBookmarkedCourses>>,
  TError = ErrorType<BookmarkedCourseListResponse[]>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBookmarkedCourses>>, TError, TData>>;
  request?: SecondParameter<typeof apiAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyBookmarkedCoursesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyBookmarkedCourses>>> = ({ signal }) =>
    getMyBookmarkedCourses(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyBookmarkedCourses>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyBookmarkedCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof getMyBookmarkedCourses>>>;
export type GetMyBookmarkedCoursesQueryError = ErrorType<BookmarkedCourseListResponse[]>;

export function useGetMyBookmarkedCourses<
  TData = Awaited<ReturnType<typeof getMyBookmarkedCourses>>,
  TError = ErrorType<BookmarkedCourseListResponse[]>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBookmarkedCourses>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBookmarkedCourses>>,
          TError,
          Awaited<ReturnType<typeof getMyBookmarkedCourses>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyBookmarkedCourses<
  TData = Awaited<ReturnType<typeof getMyBookmarkedCourses>>,
  TError = ErrorType<BookmarkedCourseListResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBookmarkedCourses>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBookmarkedCourses>>,
          TError,
          Awaited<ReturnType<typeof getMyBookmarkedCourses>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyBookmarkedCourses<
  TData = Awaited<ReturnType<typeof getMyBookmarkedCourses>>,
  TError = ErrorType<BookmarkedCourseListResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBookmarkedCourses>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 내 북마크 코스 목록 조회
 */

export function useGetMyBookmarkedCourses<
  TData = Awaited<ReturnType<typeof getMyBookmarkedCourses>>,
  TError = ErrorType<BookmarkedCourseListResponse[]>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBookmarkedCourses>>, TError, TData>>;
    request?: SecondParameter<typeof apiAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyBookmarkedCoursesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
